-- Meldpunt VWO v5 - centrale Supabase-opslag zonder Supabase Auth.
-- Voer dit bestand EEN KEER uit in Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.dm_accounts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  username text not null,
  username_key text not null unique,
  email text not null default '',
  email_notifications boolean not null default false,
  role text not null check (role in ('admin','facility','staff')),
  active boolean not null default true,
  password_hash text not null,
  password_salt text not null,
  password_cipher text not null,
  password_iv text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dm_sessions (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.dm_accounts(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table if not exists public.dm_tickets (
  id bigint generated by default as identity primary key,
  ticket_no text unique,
  reporter text not null,
  reporter_email text not null default '',
  location text not null,
  category text not null,
  urgency text not null check (urgency in ('laag','normaal','hoog','spoed')),
  title text not null,
  description text not null,
  can_continue text not null default 'ja',
  photo_path text,
  status text not null default 'open' check (status in ('open','progress','wait','done')),
  assignee uuid references public.dm_accounts(id) on delete set null,
  internal_note text not null default '',
  mail_reporter_on_complete boolean not null default false,
  completion_mail_prepared_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dm_ticket_history (
  id uuid primary key default gen_random_uuid(),
  ticket_id bigint not null references public.dm_tickets(id) on delete cascade,
  at timestamptz not null default now(),
  actor text not null,
  actor_id uuid,
  action text not null
);

create table if not exists public.dm_routing (
  category text primary key,
  account_id uuid references public.dm_accounts(id) on delete set null,
  assign_all boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.dm_routing_members (
  category text not null references public.dm_routing(category) on delete cascade,
  account_id uuid not null references public.dm_accounts(id) on delete cascade,
  primary key(category,account_id)
);

create table if not exists public.dm_ticket_assignments (
  ticket_id bigint not null references public.dm_tickets(id) on delete cascade,
  account_id uuid not null references public.dm_accounts(id) on delete cascade,
  primary key(ticket_id,account_id)
);

create table if not exists public.dm_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.dm_audit_logs (
  id uuid primary key default gen_random_uuid(),
  at timestamptz not null default now(),
  actor text not null,
  actor_id uuid,
  type text not null,
  target_id text not null default '',
  action text not null
);

create table if not exists public.dm_invites (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.dm_accounts(id) on delete cascade,
  token_hash text not null unique,
  mode text not null check (mode in ('invite','reset')),
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

insert into public.dm_settings(key,value)
values
  ('showAuditToFacility','false'::jsonb),
  ('localNotifications','true'::jsonb),
  ('reportLocationExamples','["003","105","225","Personeelswerkkamer","Mediatheek","Docentenkamer"]'::jsonb),
  ('reportTitleExamples','["Docking werkt niet","Lamp kapot","Stoel defect","Deurklink zit los","Stopcontact werkt niet"]'::jsonb),
  ('reportHeroTitle','"Facilitaire melding"'::jsonb),
  ('reportHeroIntro','"Iets kapot, vies, leeg of onveilig? Meld het hier snel bij facilitair."'::jsonb),
  ('reportHeroLocation','"Vul de locatie zo duidelijk mogelijk in, bijvoorbeeld {locaties}."'::jsonb),
  ('reportHeroEmergency','"Bij direct gevaar of spoed: volg altijd de interne noodprocedure en neem direct persoonlijk contact op."'::jsonb),
  ('reportHeroTitleSize','30'::jsonb),
  ('reportHeroIntroSize','14'::jsonb),
  ('reportHeroLocationSize','16'::jsonb),
  ('reportHeroEmergencySize','12'::jsonb)
on conflict (key) do nothing;

-- Deze tabellen worden NIET rechtstreeks vanuit GitHub Pages benaderd.
-- Alle toegang loopt via de Edge Function met een server-side secret key.
alter table public.dm_accounts enable row level security;
alter table public.dm_sessions enable row level security;
alter table public.dm_tickets enable row level security;
alter table public.dm_ticket_history enable row level security;
alter table public.dm_routing enable row level security;
alter table public.dm_routing_members enable row level security;
alter table public.dm_ticket_assignments enable row level security;
alter table public.dm_settings enable row level security;
alter table public.dm_audit_logs enable row level security;
alter table public.dm_invites enable row level security;

revoke all on table public.dm_accounts from anon, authenticated;
revoke all on table public.dm_sessions from anon, authenticated;
revoke all on table public.dm_tickets from anon, authenticated;
revoke all on table public.dm_ticket_history from anon, authenticated;
revoke all on table public.dm_routing from anon, authenticated;
revoke all on table public.dm_routing_members from anon, authenticated;
revoke all on table public.dm_ticket_assignments from anon, authenticated;
revoke all on table public.dm_settings from anon, authenticated;
revoke all on table public.dm_audit_logs from anon, authenticated;
revoke all on table public.dm_invites from anon, authenticated;

insert into storage.buckets (id, name, public)
values ('ticket-photos','ticket-photos',false)
on conflict (id) do update set public=false;
